### ISSUE TITLE
Typoscript parameter returnLast not considered

### ISSUE THREAD

**Issue by webian** [cobwebch/linkhandler#14]
Hi!
I have a typoscript that set: 
returnLast = url
(this parameter is not set in the EXT:linkhandler configuration but in a Typoscript lib that I use)

I guess that this is not considered because method 'main' in class TypolinkHandler doesn't parse $configuration variable where the returnLast parameter is present so what linkhandler returns is the full <a> tag, not only the link.

Maybe it should merge $configuration with $typoScriptConfiguration before calling typolink.

P.S.: Thanks a lot for this fork!

**Comment by fsuter** [comment]
Hmm, that could well be. I remember throwing some parts of the code which weren't really clear to me and that could have been one (it's sometimes hard when you pick up someone else's code and don't have all the related use cases).

Could you post your TS code here so that I get a better idea of the issue?

**Comment by fsuter** [comment]
Always merging configurations breaks the "usual" rendering, so I introduced a configuration parameter for triggering this behaviour. Please check the README file.

**Comment by webian** [comment]
Hi @fsuter,
thank you for the fix but unluckly it doesn't work in my use case.

First of all I'm sorry that I missed to give you more information about this issue, I was heavily busy :(

Now I try to explain the best that I can...

Considering this linkhandler TS configuration (typolinkConfiguration):
```
plugin.tx_linkhandler {
    tx_news {
        forceLink = 0
        typolink {
            parameter = 44
            additionalParams = &tx_news_pi1[news]={field:uid}&tx_news_pi1[controller]=News&tx_news_pi1[action]=detail
            additionalParams.insertData = 1
            useCacheHash = 1
        }
    }
}
```

With your example (parentTypoScriptConfiguration) it works:
```
lib.foo {
	10 = TEXT
	10 {
		typolink {
			mergeWithLinkhandlerConfiguration = 1
			parameter = record:tx_news:tx_news_domain_model_news:11 - foo "Link from TS menu"
			returnLast = url
		}
	}
}
```
Here, when parentTypoScriptConfiguration and typolinkConfiguration merge then typolink receives this configuration:
```
additionalParams = &tx_news_pi1[news]={field:uid}&tx_news_pi1[controller]=News&tx_news_pi1[action]=detail
additionalParams.insertData = 1
mergeWithLinkhandlerConfiguration = 1
parameter = 44
returnLast = url
useCacheHash = 1
```
and everything is all right.

Instead, in my use case I have a TS like this:
```
lib.foo {
	10 = TEXT
	10 {
		typolink {
			mergeWithLinkhandlerConfiguration = 1
			parameter.field = link
			returnLast = url
		}
	}
}
```
Here 'link' is the value of a field from the DB so when parentTypoScriptConfiguration and typolinkConfiguration merge then typolink receives the same configuration as before but with this added:
```
parameter.field = link
```
and then typolink returns an empty string.

Maybe it could be enough to unset this 'parameter.field = link' before calling typolink?
From what I tested it seems to work but I don't know if I'm missing something else.

**Comment by fsuter** [comment]
Thanks for the details. I will have to think how to make this possible. It is not trivial. The problem is that the typolink is rendered using a local content object. This object is loaded with the table and the record found in the "parameter" field. So there's currently no way it will know about the "link" field from whatever table you are trying to render.

**Comment by fsuter** [comment]
In French we say that "the night brings advice", I now understand what your example is. The `parameter` property will already have been interpreted when it is passed to the linkhandler. But then `parameter.field` is interpreted again by linkhandler and fails for the reason I mentioned above.

So indeed unsetting `parameter.field` is a solution, but more generally it is all `parameter.` sub-properties which should be unset, as most are likely to fail. Even more generally, this may happen with other properties of of the parent typolink configuration. And unsetting them all seems overreaching.

I'm wondering if it could be a better solution to use `insertData` for this scenario of yours:

```
lib.foo {
    10 = TEXT
    10 {
        typolink {
            mergeWithLinkhandlerConfiguration = 1
            parameter = {field:link}
            parameter.insertData = 1
            returnLast = url
        }
    }
}
```

In this case I would expect `{field:link}` to have been replaced with an actual value, which means that `insertData` would not play any role when interpreted again by linkhandler.

Does that make sense? Could you try this?

**Comment by webian** [comment]
In Italy we say the same "La notte porta consiglio", one of my favorite proverbs :+1: 

You solution to use `insertData` makes sense and it's working.
Thanks a lot for your help!

**Comment by fsuter** [comment]
You're welcome.
