### ISSUE TITLE
three parts configuration && pageTreeMountPoints (TYPO3 7.x)

### ISSUE THREAD

**Issue by linkpool** [cobwebch/linkhandler#15]
Two questions, see README.md

_"If an old link is detected that consists only of three parts the first configuration found for the linked table will be used."_

_"You can configure mount points for the page tree that is displayed in the element browser. ..." pageTreeMountPoints _

Has this been coded in the TYPO3 7.x Branch? Or only in the TYPO3 6.2 branch?

Regards,

Ra

**Comment by fsuter** [comment]
The link syntax has changed in the latest version, due to how the TYPO3 Core has changed. The README file is not up to date. In the current situation, old links will not work anymore. I suppose it could be possible to provide an upgrade wizard, but it's pretty complicated since there could be so many fields where such a link is defined.

I haven't tried mount points in this new version yet. My guess would be that they currently don't work.

**Comment by linkpool** [comment]
Hi,

I dindn't find _pageTreeMountPoints _in the source code  so i'm pretty sure that they won't work at the mement. I also took  short look at the API and could not find somehting like a filter for pids or special select statements.

I'll discuss the upgrade wizard, theme within our team. We really need this feature because in our current project there are hundreds of pages and records wilt old links. Yes, parsing the whole database would'nt be that simple. We'll think about that.

Regards Ralph

**Comment by fsuter** [comment]
You are very welcome to contribute to this project. We sure don't use all features ourselves, so there are areas which aren't looking at as closely as others.

We will probably need some update wizard too in the future, but none of our heavy linkhandler users are currently planning an upgrade to 7.

**Comment by linkpool** [comment]
I'm currently working on the RecordBrowserPageTreeView.php to get something like this:

```
TCEMAIN.linkHandler.tx_rsmbstmediathek_domain_model_rsmbstmediathekitem {
	handler = Cobweb\Linkhandler\RecordLinkHandler
	label = Mediathek
	configuration {
        table = tx_rsmbstmediathek_domain_model_rsmbstmediathekitem
        **limitUids = 173**
	}
	scanBefore = page
}
``
And then limit the Tree to those uids

Upgrade wizard / BE module would be the next feature.

**Comment by fsuter** [comment]
Unless I misunderstand your need, that's what the "storagePid" configuration option does. There's also a "hideTree" option, which entirely hides the tree, removing the need to actually navigate to the wanted folder.

Here's an example configuration:
`
TCEMAIN.linkHandler.news2 {
	handler = Cobweb\Linkhandler\RecordLinkHandler
	label = LLL:EXT:custom_config/Resources/Private/Language/locallang.xlf:tab.more_news
	configuration {
		table = tx_news_domain_model_news
		additionalWhere = AND datetime < 1420070400
		hidePageTree = 1
		storagePid = 18
	}
	scanBefore = page
}
`

**Comment by fsuter** [comment]
I know it's not documented, sorry. I didn't have time to update the documentation yet.

**Comment by linkpool** [comment]
No Problem, that's a cool feature that we can use for most of our tables,

But storagePid is a single value?

We have one table where we would like to limit to a set of pids:

```
TCEMAIN.linkHandler.tx_rsmbstpublications_publications {
	handler = Cobweb\Linkhandler\RecordLinkHandler
	label = Publikationen
	configuration {
		table = tx_rsmbstpublications_publications
        limitUids = 462,463,393
	}
	scanBefore = page
}
```

so the TreeView must me visible but is limited so a set of pids / uids.

**Comment by fsuter** [comment]
I'm not sure if storagePid must be a single value. I think so. Maybe you can expand that option rather than adding a new one?

"hideTree" is a separate option, it can be turned on/off independently.

**Comment by linkpool** [comment]
storagePid: Seems to be a limit in the core. The new property would be an extra, it can be combined.

I'lltry to have a look at a BE migration wizard tomorrow for the old styled links: Parse all text fields and find old links and replace them to the new ones.

**Comment by fsuter** [comment]
I have restored the "pageTreeMountPoints" feature in https://github.com/cobwebch/linkhandler/commit/3d3b9f52818831c955148501acdfc10e5a29221a

It will enable what you wanted to do with "limitUids".

**Comment by fsuter** [comment]
Migration tool added in https://github.com/cobwebch/linkhandler/commit/a7777b7d6242eb2d6fae1dc72d36cc46631353e0
