### ISSUE TITLE
Link is not saved after using the linkbrowser

### ISSUE THREAD

**Issue by alexanderschnitzler** [cobwebch/linkhandler#16]
When using the linkbrowser to choose a news record e.g., then a string like `record:tx_news:tx_news_domain_model_news:267` is put into the link field but it is not saved when saving the record. I guess only the value in the visible input field is changed but not in the invisible field, TYPO3 uses regularly.

**Comment by alexanderschnitzler** [comment]
<img width="1114" alt="screen shot 2016-02-10 at 13 05 34" src="https://cloud.githubusercontent.com/assets/711459/12946750/0950a9a8-cff7-11e5-8017-4afad9eaf7cf.png">

My guess was right. The images shows the markup of the link field after I have chosen a news record. The value of the hidden field still has the `1132`, the page uid that was stored before.

**Comment by fsuter** [comment]
With which version of TYPO3 are observing this behaviour? I have just tested again with 7.6.3-dev and I don't have any problem.

**Comment by alexanderschnitzler** [comment]
I am using a 7.2, but I will test this again tomorrow with a fresh instance to be sure there are no side effects of other extensions.

**Comment by fsuter** [comment]
Hmm, I would not expect linkhandler to work with 7.2. There were many changes to the Core in that area until pretty much the last minute and linkhandler builds on them.

**Comment by alexanderschnitzler** [comment]
Sorry, for sure I meant 7.6.2, not 7.2.

**Comment by alexanderschnitzler** [comment]
Just checked with a fresh installation and everything works just fine. Sorry I bothered you. Will need to find the bad guy in my installation.

**Comment by fsuter** [comment]
No worries, I'm glad there's no bug in that part ;-)

**Comment by LimeUwe** [comment]
Hi,

I just encountered the same issue today, which seems the same in this forge ticket here:
https://forge.typo3.org/issues/75743

It can be reproduced on a TYPO3 7.6.9 as follows:

1. on the SysFolder where the records are stored which are to be selected with the LinkHandler, click the  table collapse icon on the right hand side
2. with this setting, which gets stored in each user session, try to create a link with the configured LinkHandler. Now it is neccesary to click the "open table list" (un-collapse) icon on the right hand side within in the element browser pop-up tab.
3. now click on one of the records to create the link in the link field

After this, the link handler string shows up in the input field, but is not changed in the hidden field, which keeps the actual value to be written to the database.

If the records table is already opened in the pop-up window of the element browser tab, everthing works just fine.

**Comment by fsuter** [comment]
Thanks for the detailed report. I'll try to take a look at some point, but I have no time now, sorry.

**Comment by linkpool** [comment]
Maybe the same issue:
If you use the search-for filter inside the LinkHandler-Popup and select an record item afterwards, the link won't be saved. 
If you directly select the same item - without having searched for it - the link will be saved.
