### ISSUE TITLE
Render correct link when insert a link in extension rte

### ISSUE THREAD

**Issue by stephangrass** [cobwebch/linkhandler#18]
Hi,
thanks for this fork.
I try using linkhandler in TYPO3 7LTS with my own extension. All will work, if I insert an links to records of my extension in standard content elements.

But when I link to a record of my extension in the RTE from another record of my extension the link will not rendered  correctly in the frontend. It looks like "record:tx_myext:tx_myext_domain_model_data:10"

My Page TS:
TCEMAIN.linkHandler.tx_myext {
	handler = Cobweb\Linkhandler\RecordLinkHandler
	label = Produkte
	configuration {
		table = tx_myext_domain_model_data
	}
	scanBefore = page
}

My TS

plugin.tx_linkhandler {
    tx_myext {
        listTables = tx_myext_domain_model_data
        typolink {
            parameter = {field:pid}
            parameter.insertData = 1
            additionalParams = &tx_myext_data[data]={field:uid}
            additionalParams.insertData = 1
            useCacheHash = 1
        }
    }
}

Is this a bug or is smething wrong with my configuration?

Thanks
Stephan

**Comment by fsuter** [comment]
The configuration looks generally good. I wonder about the `parameter = {field:pid}` setting though. Are your records indeed meant to be displayed on the page where they are stored? Or do you have a separate page for the detailed view of your records?

Other question: does the link in the RTE have the attributes `data-htmlarea-external="1" rtekeep="1"`? I have just noticed that this happens in some cases and the link then does not get interpreted in the frontend. I'm not yet sure when this happens and I suspect it is a Core bug.

Could you post the full code of your link as it appears in the RTE?

**Comment by stephangrass** [comment]
> I wonder about the parameter = {field:pid} setting though.
Yes, the my records must displayed on the page where they are stored.

This will be the real link code in the RTE
<a href="record:tx_racktimeproducts:tx_racktimeproducts_domain_model_products:17">Kunststoff</a>

**Comment by fsuter** [comment]
Hmm, I guess your markup was removed. You should put code between backquotes (\`).

**Comment by stephangrass** [comment]
plse reload

**Comment by fsuter** [comment]
Better :-)

But weird, because your link is very simple, with no attributes. If the linkhandler was not finding the configuration, you should see a big, red error message in your text... It's as if the linkhandler was not called at all.

Can you debug the situation?

**Comment by stephangrass** [comment]
The link schown in the frontend is exacly the same as in the RTE. So yes, the linkhandler was not called. I don't know why. In normal content-elements on the same page, linkhandler was called and worked perfectly.

**Comment by fsuter** [comment]
You mean the link is in a RTE field that is part of your record? It should still work, unless your field is not parsed at all. I must say I have no idea what's wrong in your situation.

**Comment by stephangrass** [comment]
The RTE in my extension will not handle the links correctly. The links will not convert to `<link></link>`. The links will stored as normal HTML-links in the database. 

It's not a linkhandler-problem. Sorry...

**Comment by fsuter** [comment]
No problem. I hope you find the solution to your issue.
