### ISSUE TITLE
Git versioning / tagging

### ISSUE THREAD

**Issue by ogrosko** [cobwebch/linkhandler#19]
Hey

Would be possible to create git tag for stable version of linkhandler. To be able to use as composer version ...
Now I'm using `"cobweb/linkhandler": "dev-master"` and by the development process some bugs can get to my site.

Thanks

**Comment by fsuter** [comment]
Yes, it's possible. I would like to finish work on the link validator part, and then I would consider this version stable.

I'm not familiar with the needs of composer. What kind of tag do you need? Is there a specific naming convention?

**Comment by ogrosko** [comment]
There are multiple ways to specify version see [https://getcomposer.org/doc/02-libraries.md#specifying-the-version](url)

**Comment by fsuter** [comment]
I just tagged a "v3.0.0" release. I hope this is what you needed.

**Comment by ogrosko** [comment]
Great :+1: 
Really thank you

just for note see following composer.json code:
Now it's  possible reference to specific stable version

`{
	"name": "some/name",
    "type": "Typo3",
    "description": "",
    "homepage": "",
    "keywords": ["TYPO3 CMS"],
    "version": "0.0.1",

	"repositories": [
        {
            "type": "composer",
            "url": "https://composer.typo3.org/"
        },
        {
            "type": "git",
            "url": "https://github.com/cobwebch/linkhandler.git"
        }
    ],

    "require": {
        "typo3/cms": "7.6.4",
        "cobweb/linkhandler": "3.0.0"
    }
}
`

**Comment by ogrosko** [comment]
After you create new version 3.1.0 you tag it as 3.1.0
Please use the same tagging convention as you begin with v3.0.0

Now it's not possible to target composer to newest version 3.1.0 (please tag it as v3.1.0)

Thank you very much

**Comment by fsuter** [comment]
Oh sorry. Done with a new release.

**Comment by ogrosko** [comment]
Thank you for your urgent reply :+1: 
One last thing I hope change the version in composer.json to 3.1.0

**Comment by fsuter** [comment]
:-(

**Comment by fsuter** [comment]
Will do a 3.1.1 release with updated versions everywhere (hopefully).

**Comment by ogrosko** [comment]
:+1:

**Comment by fsuter** [comment]
I hope it's all okay now with v3.1.1.

**Comment by ogrosko** [comment]
:+1:  yes it works
