### ISSUE TITLE
Add the package in Packagist

### ISSUE THREAD

**Issue by marcosalberto** [cobwebch/linkhandler#23]
As the repository is public and it's here on Github, it´s needed use a token access to download the package with Composer.

Add to Packagist fixes the problem, if this is considered a problem.

**Comment by fsuter** [comment]
I understand. However this fork was never meant to be an official version of the extension, although it became one over time, which means I have no intention to release it to the TER not to put it up on Packagist. Sorry.

I have had recent contact with AOE and they mean to pick up the work again. Maybe they will be willing to register this extension on Packagist.

**Comment by marcosalberto** [comment]
Packagist is not the official repository composer of the TYPO3, exists the [https://composer.typo3.org/](https://composer.typo3.org/) to the official extensions. Add to Packagist will not cause any problem, of course if you want to keep the repository.

Thanks by explain.
