### ISSUE TITLE
question because of different detail pages

### ISSUE THREAD

**Issue by blueamerican** [cobwebch/linkhandler#32]
hi,

the extension works fine in typo3 v7.

is there a possibility link to different detailpages according to the storage pids?

or can i only habe one detail link.

plugin.tx_linkhandler.tx_news.typolink.parameter = 42

**Comment by fsuter** [comment]
Sorry for the delay in answering, I was on holiday. You can define only a single detail page per TypoScript, but you can achieve what you want using the "generateLink" hook found in class `Cobweb\Linkhandler\ TypolinkHandler`.

**Comment by blueamerican** [comment]
ok thanks
