### ISSUE TITLE
Class 'Cobweb\Linkhandler\RecordLinkHandler' not found 

### ISSUE THREAD

**Issue by twirsing** [cobwebch/linkhandler#33]
I receive this messege when trying to set a link within RTE under Typo3 7.6.10. Extension is installed, shown under "Installed Extensions" and I have added a configuration for page ts. Probably I am missing something and it is no bug.

My configuration:
TCEMAIN.linkHandler.tx_xxxxx_project {
    handler=Cobweb\Linkhandler\RecordLinkHandler
    label=MyProjects
    configuration {
        table = tx_xxxxx_project
        storagePid = 64
    }
    displayAfter = page
    scanAfter = page
}

**Comment by fsuter** [comment]
Hmm, your configuration looks okay and should work. Maybe you have some cache issue. Try deleting the "typo3temp/autoload" folder and see if it helps.

**Comment by twirsing** [comment]
Thanks, for the quick reply and sorry for the late feedback. In fact your suggestion work perfectly. After deleting the cached files, the wizard worked as expected.
Cheers, twirsing

**Comment by fsuter** [comment]
Great!
