### ISSUE TITLE
Hook example

### ISSUE THREAD

**Issue by basvandertogt** [cobwebch/linkhandler#34]
Can somebody give me an example how to use the hook?

**Comment by fsuter** [comment]
Hi Bas,

Here's an example. When handling news items, we have different detail pages depending on the category each news item belongs to:

```
class Linkhandler {
	/**
	 * Changes target page based on sys_category relations for news records.
	 *
	 * @param \tx_linkhandler_handler $pObj Back-reference to calling object
	 * @param string $recordTableName Name of the table being linked to
	 * @param integer $recordUid Id of the record being linked to
	 * @param integer $currentParameter Id of current target page
	 * @return mixed
	 */
	public function parameterChanger($pObj, $recordTableName, $recordUid, $currentParameter) {

		// For other records than news, leave parameter unchanged
        if ($recordTableName != 'tx_news_domain_model_news') {
			return $currentParameter;
		}

        // Get the news detail link from the reference page specified in the category
        $selectFields = 'sys_category.single_pid';
        $fromTables = 'tx_news_domain_model_news
                        LEFT JOIN sys_category_record_mm
                        ON  tx_news_domain_model_news.uid = sys_category_record_mm.uid_foreign
						AND tablenames = \'tx_news_domain_model_news\'
						AND fieldname = \'categories\'
                        LEFT JOIN sys_category
                        ON sys_category.uid = sys_category_record_mm.uid_local';
        $where = 'tx_news_domain_model_news.uid = ' . intval($recordUid);

        $rows = $GLOBALS['TYPO3_DB']->exec_SELECTgetRows(
			$selectFields,
			$fromTables,
			$where
		);

        if ($rows && count($rows) > 0 && $rows[0]['single_pid'] !='') {
            return $rows[0]['single_pid'];
        } else {
            return $currentParameter;
        }

    }
}
```

I hope this helps you.

**Comment by basvandertogt** [comment]
Thank you very much for your reply!

However i get the error: Class 'Vendor\Bla\Hooks\Linkhandler' not found in ...

Bu in my extension ext_localconf.php i have set: $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['linkhandler']['generateLink'][] = 'Vendor\Bla\Hooks\Linkhandler';

And the class file is here: typo3conf/ext/Vendor/Classes/Hooks/Linkhandler.php

Anu idea?

**Comment by fsuter** [comment]
Have you just added your class? I have found that the autoloader does not automatically detect classes which were just added to an extension undergoing development, as the autoloader cache is flushed only upon installation/deinstallation. You should try deleting the "typo3temp/autoload" folder. HTH

**Comment by basvandertogt** [comment]
You're right. After i removed the autoload directory, the class was loaded correctly. But now i'm facing the next problem; it looks like the parameterChanger function is not callt. I've put an exit on top of the function but it's not working.

**Comment by fsuter** [comment]
Ah yes, sorry. My example if from an older version of TYPO3. The function must now be called simply `process` and the class must implement the `\Cobweb\Linkhandler\ProcessLinkParametersInterface` interface. It's way more general than what was available in the older version of linkhandler. You simply get a back-reference to the `\Cobweb\Linkhandler\TypolinkHandler`, which has a lot of getters and setters allowing to manipulate stuff pretty much as you wish.

Sorry for the confusion.

**Comment by basvandertogt** [comment]
Tnx, i got it work now:

`
<?php
namespace Vendor\Bla\Hooks;

use TYPO3\CMS\Extbase\Utility\DebuggerUtility;

class Linkhandler implements \Cobweb\Linkhandler\ProcessLinkParametersInterface {

	public function process($linkHandler) {

//		DebuggerUtility::var_dump($linkHandler);

		if ($linkHandler->getTable() == 'tx_sis_domain_model_hotel') {
			$record = $linkHandler->getRecord();

			if ($record['groupretreatvenue'] == 1) {
				$typolinkConfiguration = $linkHandler->getTypolinkConfiguration();
				$typolinkConfiguration['parameter'] = 46;

				$linkHandler->setTypolinkConfiguration($typolinkConfiguration);
			}
		}
	}
}
`

**Comment by fsuter** [comment]
Great!

**Comment by stadtkonzeptbasel** [comment]
hi @fsuter do you have a working hook for the tx_news single pid set by sys_category?
Couldn't get your example to work.

**Comment by cornerfarmer** [comment]
I made the hook example of @fsuter working with the current version.
For everyone who has the same problem:

```php
class Linkhandler implements \Cobweb\Linkhandler\ProcessLinkParametersInterface {

    public function process($linkHandler) {

        // For other records than news, leave parameter unchanged
        if ($linkHandler->getTable() != 'tx_news_domain_model_news') {
            return;
        }

        $typolinkConfiguration = $linkHandler->getTypolinkConfiguration();

        // Get the news detail link from the reference page specified in the category
        $selectFields = 'sys_category.single_pid';
        $fromTables = 'tx_news_domain_model_news
                        LEFT JOIN sys_category_record_mm
                        ON  tx_news_domain_model_news.uid = sys_category_record_mm.uid_foreign
                        AND tablenames = \'tx_news_domain_model_news\'
                        AND fieldname = \'categories\'
                        LEFT JOIN sys_category
                        ON sys_category.uid = sys_category_record_mm.uid_local';
        $where = 'tx_news_domain_model_news.uid = ' . intval($linkHandler->getUid());

        $rows = $GLOBALS['TYPO3_DB']->exec_SELECTgetRows(
            $selectFields,
            $fromTables,
            $where
        );

        if ($rows && count($rows) > 0 && $rows[0]['single_pid'] !='') {
            $typolinkConfiguration['parameter'] = $rows[0]['single_pid'];
            $linkHandler->setTypolinkConfiguration($typolinkConfiguration);
        }

    }
}
```
