### ISSUE TITLE
This extension is missing on https://composer.typo3.org

### ISSUE THREAD

**Issue by igodorogea** [cobwebch/linkhandler#36]
The package "cobweb/linkhandler" is no longer available on TYPO3 composer repository.

I believe a couple of months ago I was able to install this extension without specifying current git repo inside the root composer.json(repositories array).
When did this change?

**Comment by fsuter** [comment]
I would say you were probably referencing the old linkhandler version, which is not compatible with TYPO3 6.2 and above. This current version of linkhandler is only to be found on GitHub, so there's no choice but to reference this repository.

**Comment by igodorogea** [comment]
Hmm, I'm almost pretty sure I've installed this ext with `composer require cobweb/linkhandler`.
Here is a snippet from composer.lock file from mid june:
```json
{
	"name": "cobweb/linkhandler",
	"version": "3.1.1",
	"source": {
		"type": "git",
		"url": "https://github.com/cobwebch/linkhandler.git",
		"reference": "674d89bde00e1c9a10b8142fcd4a178fe61e857d"
	},
	"dist": {
		"type": "zip",
		"url": "https://api.github.com/repos/cobwebch/linkhandler/zipball/674d89bde00e1c9a10b8142fcd4a178fe61e857d",
		"reference": "674d89bde00e1c9a10b8142fcd4a178fe61e857d",
		"shasum": ""
	},
	"require": {
		"typo3/cms-core": ">=7.6.1,<8.0"
	},
	"replace": {
		"cobweb/linkhandler": "*"
	},
	"type": "typo3-cms-extension",
	"autoload": {
		"psr-4": {
			"Cobweb\\Linkhandler\\": "Classes"
		}
	},
	"notification-url": "https://packagist.org/downloads/",
	"license": [
		"GPL-2.0+"
	],
	"authors": [
		{
			"name": "Francois Suter",
			"role": "Developer"
		}
	],
	"description": "Create links to any record (e.g. news)",
	"homepage": "http://typo3.org",
	"time": "2016-03-21 17:24:02"
},
```

Was it available on packagist in this period(mid june 2016)?

**Comment by fsuter** [comment]
Well, I don't know what to say. The sure thing is that the linkhandler version in this repository has never been released to TER. I also did nothing with regards to Packagist. Maybe there's some automation somewhere or something done by some member of the community, but I'm unaware of that. Sorry.

**Comment by iamandrewluca** [comment]
I added to `composer.json`
```
{
    "type": "git",
    "url": "https://github.com/cobwebch/linkhandler.git"
}
```
And when require, still don't get last version `3.1.2` it gets only `3.1.1`

**Comment by igodorogea** [comment]
@fsuter said:
> Sorry.

Don't be. This is most like a confusion then an issue.

@iamandrewluca your problem is not related to this issue. You may look into composer or TYPO3 composer installers or create a separate issue.

**Comment by iamandrewluca** [comment]
Will be this extension added to TYPO3 TER in future?

**Comment by fsuter** [comment]
The goal is to make it part of the Core for 8 LTS.
