### ISSUE TITLE
TYPO3 6.2 compatibility

### ISSUE THREAD

**Issue by tritumRz** [cobwebch/linkhandler#7]
Hi, this is a first attempt for TYPO3 6.2 compatibility:

https://github.com/tritumRz/linkhandler/commit/d50481966876db97a773c43f55416066ea8ac710

**Comment by SventB** [comment]
On your project start page you write

> Additionally, all legacy code was removed, the goal is to provide a version that is compatible with TYPO3 6.2.

This seems not to be correct any more, your linkhandler fork is compatible with TYPO3 7.2.

**Comment by fsuter** [comment]
Thanks for noticing. Information updated in commit https://github.com/cobwebch/linkhandler/commit/3d62c460c2658efc75b5210f0ee05de69c432fb2

**Comment by SventB** [comment]
Now you write
> For a version compatible with TYPO3 CMS 6.2, please use the TYPO3_6-2 branch.

But this branch is VERY old. Why didn't you make a branch before commit "Merged changes from intera fork (branch TYPO3_6-2)", at this point:
https://github.com/cobwebch/linkhandler/tree/88a76a79864b39bdcceb1471cec5ffbf1416a8a7

There, everything seems to work with TYPO3 6.2.

**Comment by fsuter** [comment]
Hmm, I must admit I somewhat lost track of which extension version is compatible with which TYPO3 version. I'm sorry if my information is confusing. I don't really have time to look more deeply at this now.
